### ISSUE TITLE
RPC page issue

### ISSUE THREAD

**Issue by sophoah** [harmony-one/elastic-rpc-infra#17]
when we call an API that requires a page number (say getAllValidatorInformationByBlockNumber) there is some likelihood for common or repeated validators across pages. I suspect that this happens because reader 1 answers the first query while the second query is answered by another reader.

**Comment by MaxMustermann2** [comment]
This issue could not be reproduced, perhaps the report was a fluke. 

Can you please close it? I don't have rights.
